server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerDB
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

ACCOUNT-SERVICE-URL: http://ACCOUNT-SERVICE/accounts/

#eureka configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
